// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HostAPI {
  func ping() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HostAPISetup {
  /// The codec used by HostAPI.
  /// Sets up an instance of `HostAPI` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HostAPI?) {
    let pingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_dart_impl_sample.HostAPI.ping", binaryMessenger: binaryMessenger)
    if let api = api {
      pingChannel.setMessageHandler { _, reply in
        do {
          let result = try api.ping()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pingChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class FlutterAPI {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  func ping(completion: @escaping (String) -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shared_dart_impl_sample.FlutterAPI.ping", binaryMessenger: binaryMessenger)
    channel.sendMessage(nil) { response in
      let result = response as! String
      completion(result)
    }
  }
}
